// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkbhwoumdbqqwzzefjhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYmh3b3VtZGJxcXd6emVmamhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDcxOTUsImV4cCI6MjA2OTA4MzE5NX0.eTaYY1lYaTP9Q5Cx0Tmjv5vto1VA3_k6r8Qv7XM2HQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});